apiVersion: v1
kind: Service
metadata:
  name: resend-mailer
  namespace: mailapi
  labels:
    app.kubernetes.io/name: resend-mailer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: resend-mailer
